# Generated by Django 5.2.4 on 2025-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_created_at_profile_location_profile_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("TOPS", "Tops"),
                    ("BOTTOMS", "Bottoms"),
                    ("DRESSES", "Dresses"),
                    ("OUTERWEAR", "Outerwear"),
                ],
                max_length=20,
            ),
        ),
    ]
